IizakaEmpire/IizakaEmpire/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from .sitemaps import MyBlogSitemap,StaticSitemap

sitemaps={
    'blog':MyBlogSitemap,
    'static':StaticSitemap,
}

urlpatterns = [
    path('',include('MyBlog.urls',namespace='AdHnd')),
    path('admin/', admin.site.urls),
    path('markdownx/',include('markdownx.urls')),
    path('sitemap.xml',sitemap,{'sitemaps' : sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

IizakaEmpire/MyBlog/urls.py
from django.urls import path,include

from . import views

app_name='MyBlog'

urlpatterns = [
    path('',views.index,name='index'),
    path('blog/<slug:div>/<slug:blog_id>/',views.blog,name='blog'),
    path('search/<slug:type>/<int:searchtype>/',views.Categorys,name='search'),
    path('markdownx/',include('markdownx.urls')),
]

IizakaEmpire/MyBlog/models.py
from django.db import models
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=16)
    slug=models.SlugField(max_length=8,unique=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name=models.CharField(max_length=16)
    slug=models.SlugField(max_length=8,unique=True)
    
    def __str__(self):
        return self.name

class Article(models.Model):
    slug=models.SlugField(max_length=16,unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    tags=models.ManyToManyField(Tag)
    title=models.CharField(max_length=64)
    meta_description=models.CharField(max_length=64)
    ogp_title=models.CharField(max_length=32)
    ogp_img=models.ImageField(upload_to='ogp_img')
    pub_date=models.DateTimeField('作成日時',auto_now_add=True)
    up_date=models.DateTimeField('更新日時',auto_now=True)
    contents=MarkdownxField('Contents',help_text='box9 is note box<div>')
    
    def __str__(self):
        return self.title

    class Meta:
        ordering=['-pub_date']

    def exchange_markdown(self):
        return markdownify(self.contents)

   # def get_absolute_url(self):
    #    return reverse('MyBlog:blog',kwargs={
     #       'div':self.category.slug,
      #      'blog_id':self.slug,
       # })

class Author(models.Model):
    profimg=models.ImageField(upload_to='author/')
    name=models.CharField(max_length=16)
    contents=MarkdownxField('Contents',help_text='To Put your profile')

    def __str__(self):
        return self.name
    
    def exchange_markdown(self):
        return markdownify(self.contents)

IizakaEmpire/MyBlog/views.py
from django.shortcuts import render,get_list_or_404,get_object_or_404
from django.core.paginator import Paginator
from django.http import HttpResponse,Http404
from .models import Article,Author,Category
# Create your views here.

def index(request):

    try:
        article=Article.objects.all().values_list('slug','ogp_title','meta_description','ogp_img','pub_date','category')
    
        article_List=[]

        for art in article:
            tmp=Category.objects.get(id=art[5])
            tmp_tuple=(tmp.slug,tmp.name)
            article_List.append(art+tmp_tuple)

        author=Author.objects.all()

        pagenate=Paginator(article_List,5)

        if request.GET:
            p=request.GET.get('page')
            p=int(p)
        else:
            p=1

        putart=pagenate.get_page(p)
        page_num=pagenate.page_range
    
        contents={
            'author':author,
            'article':putart,
            'page_num':page_num,
            'current_page':p,
        }

        return render(request,'index.html',contents)
    except (KeyError,Article.DoesNotExist):
        return Http404("お探しのコンテンツが見つかりませんでした。\n")
    else:
        return HttpResponse("障害が発生中です。\nお時間を置いてのアクセスをお願い致します。")

def blog(request,div,blog_id):
    
    putart=get_object_or_404(Article,slug=blog_id)
    recommend=Article.objects.all().values_list('slug','ogp_title','ogp_img','category')[:4]

    recommend_List=[]

    for art in recommend:
        tmp=Category.objects.get(id=art[3])
        tmp_tuple=(tmp.slug,tmp.name)
        recommend_List.append(art+tmp_tuple)

    tags_list=putart.tags.all()
    contents={
        'article':putart,
        'recommend':recommend_List,
        'tags':tags_list,
        'category':putart.category,
    }

    return render(request,'blog.html',contents)

def Categorys(request,type,searchtype):

    try:
        if searchtype==1:
            article=Article.objects.select_related('category').filter(category__slug=type).values_list('slug','ogp_title','meta_description','ogp_img','pub_date','category')
        elif searchtype==2:
            article=Article.objects.select_related('tags').filter(tags__slug=type).values_list('slug','ogp_title','meta_description','ogp_img','pub_date','category')
        else:
            return Http404
    
        article_List=[]

        for art in article:
            tmp=Category.objects.get(id=art[5])
            tmp_tuple=(tmp.slug,tmp.name)
            article_List.append(art+tmp_tuple)

        author=Author.objects.all()

        pagenate=Paginator(article_List,5)

        if request.GET:
            p=request.GET.get('page')
            p=int(p)
        else:
            p=1

        putart=pagenate.get_page(p)
        page_num=pagenate.page_range
    
        contents={
            'author':author,
            'article':putart,
            'page_num':page_num,
            'current_page':p,
        }

        return render(request,'index.html',contents)
    except (KeyError,Article.DoesNotExist,Category.DoesNotExist):
        return Http404("お探しのコンテンツが見つかりませんでした。\n")
    else:
        return HttpResponse("障害が発生中です。\nお時間を置いてのアクセスをお願い致します。")

IizakaEmpire/MyBlog/templates/blog.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="{{article.meta_description}}">
        <meta property="og:url" content="{% url 'blog' article.category.slug article.slug %}">
        <meta property="og:title" content="{{article.ogp_title}}">
        <meta proparty="og:description" content="{{article.meta_description}}">
        <meta proparty="og:image" content="{{article.ogp_img.url}}">
        <meta proparty="og:type" content="{{article.category.slug}}">
        <meta proparty="og:site_name" content="AdmiralHondaの航海日誌">
        <meta proparty="og:locale" content="ja_JP">

        {%load static%}
        <link rel="stylesheet" type="text/css" href="{%static 'blog.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <title>{{article.title}}</title>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div  class="col-xs-12" style="background-color: darkcyan;color:white;">
                    <h1>Blog of AdmiralHonda</h1>
                    <p>プログラミングや趣味のアウトドアについて色々</p>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <center>
                        <h1>
                            {{article.title}}
                        </h1>
                    </center>
                    <p style="float: right;">更新日<br>{{article.up_date}}</p>
                    {%if category%}
                    <button class="btn-square-shadow" onclick="location.href='{% url 'MyBlog:search' category.slug 1 %}'">{{category.name}}</button>
                    <br>
                    {%else%}
                    {%endif%}
                    {%if tags %}
                    {% for tag in tags %}
                    <button class="btn-square-shadow" onclick="location.href='{%url 'Myblog:search' tag.slug 2 %}'">{{tag.name}}</button>
                    {%endfor%}
                    {%else%}
                    {%endif%}
                    <article>
                        {{article.exchange_markdown|safe}}
                    </article>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3"></div>
                <div class="col-xs-2">
                    <button><</button>
                </div>
                <div class="col-xs-2">
                    <button onclick="location.href='{%url 'MyBlog:index'%}'">home</button>
                </div>
                <div class="col-xs-2">
                    <button>></button>
                </div>
                <div class="col-xs-3"></div>
            </div>
            <div class="row">
                {%if recommend%}
                {% for article in recommend %}
                    <div class="col-xs-3">
                        <a href="{% url 'MyBlog:blog' article.4 article.0 %}">
                            <div class="thumbnail">
                                <img src="{{MEDIA_URL}}{{article.2}}" style="width: 100;" alt="srticle.0">
                            </div>
                            <div class="caption">
                                <p>{{article.1}}</p>
                            </div>
                        </a>
                    </div>
                {%endfor%}
                {%else%}
                {%endif%}
            </div>

        </div>
        <!--page end-->
    </body>
</html>

IizakaEmpire/MyBlog/templates/index.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="dscription" content="AdmiralHondaの人生という航海の中での日誌">
        <title>AdmiralHondaの航海日誌</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{%static 'index.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    
    <body>
        <div class="container">
            <!--header-->
            <div class="row">
                <div  class="col-xs-12" style="background-color: darkcyan;color:white;">
                    <h1>Blog of AdmiralHonda</h1>
                    <p>プログラミングや趣味のアウトドアについて色々</p>
                </div>
            </div>
            <!--ArticleList-->
            <div class="row">
                <div class="col-xs-8">
                    <h3>最近の更新</h3>
                    {% if article %}
                    {% for topic in article %}
                    <div class="box7">
                        <p>{{topic.4}}</p>
                        <button class="btn-square-shadow" onclick="location.href='{% url 'MyBlog:search' topic.6 1 %}'">{{topic.7}}</button>
                        <div class="media-left">
                            <img src="{{MEDIA_URL}}{{topic.3}}" class="media-object" style="width: 250px;height:250px">
                        </div>
                        <div class="media-body">
                            <h3 class="media-heading">{{topic.1}}</h3>
                            <p>{{topic.2}}</p>
                        </div>
                        <center>
                            <button class="btn-square-slant" onclick="location.href='{% url 'MyBlog:blog' topic.6 topic.0 %}'">READ MORE</button>
                        </center>
                    </div>
                    {% endfor %}
                    <center>
                    <ul class="pagination">
                        <!--{%if previous_page%}
                        <li><a href="?page={{previous_page}}">前のページ</a></li>
                        {%else%}
                        {%endif%}-->
                            {%for page in page_num%}
                            {%if page == current_page %}
                            <li class="active"><a href="?page={{page}}">{{page}}</a></li>
                            {%else%}
                            <li><a href="?page={{page}}">{{page}}</a></li>
                            {%endif%}
                            {%endfor%}
                            <!--
                        {%if next_page%}
                        <li><a href="?page={{next_page}}">次のページ</a></li>
                        {%else%}
                        {%endif%}-->
                      </ul>
                      </center>
                    {% else %}
                    <p>ただいま障害が発生中です。少々お待ちください</p>
                    {% endif %}
                </div>
                <div class="col-xs-4">
                    <div class="box27">
                        <span class="box-title">Author</span>
                        {%if author%}
                        <center>
                            <img src="{{author.0.profimg.url}}" style="width: 200px;height:200px">
                            </center>
                            <h4>{{author.0.name}}</h4>
                            {{author.0.exchange_markdown|safe}}
                        {%else%}
                        <p>まだないみたい</p>
                        {%endif%}
                    </div>
                    <!--↑profile-->
                </div>
                <!--↑-->
            </div>
        </div>
    </body>
</html>